# ruff: noqa: E501  (long table text)
"""Sanity check of the engines on synthetic inputs against published ranges.

Run: python analysis/sanity_check.py   (writes docs/sanity-check.md; about 2 minutes)

Every published figure below was read from the cited paper; where no
published figure was found the row says "awaiting source" and nothing is invented. Synthetic inputs only.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from cardiac_capacity import (
    casemix,
)
from cardiac_capacity import (
    cicu_policy as cp,
)
from cardiac_capacity import (
    parameter_sets as ps,
)
from cardiac_capacity import (
    ward_referral_v2 as w2,
)
from cardiac_capacity.stats import mean_ci, wilson_interval
from cardiac_capacity.ward_referral import DEFAULT_PARAMS

OUT = Path(__file__).resolve().parents[1] / "docs" / "sanity-check.md"
N = 100
WEEKS = 52


def ci(values: list[float], fmt: str = "{:.1f}") -> str:
    m, lo, hi = mean_ci(values)
    return f"{fmt.format(m)} [{fmt.format(lo)}, {fmt.format(hi)}]"


def cicu_block(label: str, params: cp.PolicyParams) -> dict[str, str]:
    ms = cp.replicate(params, WEEKS, N, 1000)
    return {
        "label": label,
        "occ": ci([100 * m.mean_occupancy for m in ms], "{:.0f}") + " %",
        "stay": ci([m.mean_stay for m in ms], "{:.2f}"),
        "wait": ci([m.mean_wait_at_surgery for m in ms], "{:.1f}"),
        "over26": ci([m.over_26_end for m in ms], "{:.1f}"),
        "det": ci([m.det_events for m in ms], "{:.1f}"),
        "list_end": ci([m.list_end for m in ms], "{:.0f}"),
        "full": ci([100 * m.days_full for m in ms], "{:.1f}") + " %",
    }


def main() -> None:
    lit, plc = ps.LITERATURE, ps.PLACEHOLDERS
    blocks = [
        cicu_block("CICU, placeholders", cp.PolicyParams(deterioration_rates=plc.cicu_rates())),
        cicu_block("CICU, literature-based", cp.PolicyParams(deterioration_rates=lit.cicu_rates())),
        cicu_block(
            "CICU + case mix, literature-based",
            cp.PolicyParams(deterioration_rates=lit.cicu_rates(), casemix=casemix.DEFAULT_CASEMIX),
        ),
        cicu_block(
            "CICU settled start, literature-based",
            cp.PolicyParams(deterioration_rates=lit.cicu_rates(), start_mode="settled"),
        ),
    ]
    # Case-mix self-consistency: simulated interstage deaths versus the sourced 8 %.
    cm = cp.PolicyParams(deterioration_rates=lit.cicu_rates(), casemix=casemix.DEFAULT_CASEMIX)
    big = cp.replicate(cm, 260, 30, 5000)  # five years, to collect HLHS patients
    deaths = sum(m.interstage_deaths for m in big)
    hlhs_ops = float(sum(m.stage1_operated for m in big))
    lo, hi = wilson_interval(deaths, int(hlhs_ops))

    # Ward v2 default scenario.
    ward = [
        w2.run_simulation(dict(DEFAULT_PARAMS), [], WEEKS, 2000 + i, detail=False) for i in range(N)
    ]
    ward_occ = [float(f["occupancy"].mean()) for f in ward]
    ward_breach = [float(f["Over_26_Wks"].iloc[26]) for f in ward]
    ward_det = [float(f["det_events"].sum()) for f in ward]
    d = DEFAULT_PARAMS
    los = [d[f"los_cat{i}"] for i in range(1, 6)]
    dist = np.array([d[f"dist_cat{i}"] for i in range(1, 6)], dtype=float)
    ward_los_mean = float((los * dist).sum() / dist.sum())

    cum = lambda p, k=26: 1 - (1 - p) ** k  # noqa: E731
    names = ("2 to 1", "3 to 2", "4 to 3", "5 to 4")
    det_model = "; ".join(
        f"cat {n}: placeholders {plc.rates[i]:.0%}/wk ({cum(plc.rates[i]):.0%} in 26 wk), literature {lit.rates[i]:.2%}/wk ({cum(lit.rates[i]):.0%} in 26 wk)"
        for i, n in enumerate(names)
    )

    text = (
        f"""# Sanity check: engines on synthetic inputs versus published ranges

Generated by `analysis/sanity_check.py` ({N} seeds per scenario, {WEEKS}-week horizon, synthetic inputs, no real data).
Intervals are normal-approximation 95% CIs for means. "Published" figures were read from the sources named in each row.
**Verdict key:** consistent = inside the published range; plausible = same order of magnitude, different population or measure;
cannot judge = no comparable published figure was found (**awaiting source**).

## 1. What the engines produced

Scenario: 5 elective slots a week, 10 CICU beds, 5 referrals a week, 60 on the list at the start, default category mix
(5/15/30/50%), occupancy ceiling 85%.

| Run | Mean CICU occupancy | Days with every bed full | Mean stay of operated patients (days) | Mean wait at surgery (weeks) | Waiting 26+ weeks at week 52 | Deteriorations in 52 weeks | List at week 52 |
|---|---|---|---|---|---|---|---|
"""
        + "\n".join(
            f"| {b['label']} | {b['occ']} | {b['full']} | {b['stay']} | {b['wait']} | {b['over26']} | {b['det']} | {b['list_end']} |"
            for b in blocks
        )
        + f"""

Ward engine v2, default scenario (6 referrals a week, 5 slots, 8 beds, placeholders): mean ward occupancy
{ci(ward_occ, "{:.1f}")} of 8 beds; 26+ week waits at week 26 {ci(ward_breach, "{:.1f}")}; deteriorations in 52 weeks
{ci(ward_det, "{:.0f}")}; mean ward stay of the default mix {ward_los_mean:.1f} days (model input).

Self-consistency of the case-mix model: with the sourced interstage mortality of 8% for HLHS stage 1, the simulation recorded
{deaths} interstage deaths in about {hlhs_ops:.0f} stage-1 patients over 30 five-year runs ({deaths / hlhs_ops:.1%}, Wilson 95% {lo:.1%} to {hi:.1%}).

## 2. Comparison table

| Quantity | Model (synthetic default) | Published range or value | Source | Verdict |
|---|---|---|---|---|
| CICU stay by category | 14 / 10 / 5 / 3 days (urgent to routine), mean {sum(w * x for w, x in zip((0.05, 0.15, 0.3, 0.5), (14, 10, 5, 3), strict=True)):.1f} days for the default mix; simulated mean {blocks[0]["stay"]} | TGA arterial switch: ICU median 7 days (IQR 5-11), n = 1,772. Norwood: ICU mean 19.6 ± 20.6 days (3 studies, 183 patients). Stage II palliation: ICU mean 5 days (n = 22). Coarctation stent: ICU 5 ± 3.4 days (n = 10) | Dorobantu et al. 2023, doi:10.1016/j.jacadv.2023.100407; Iskander et al. 2024, doi:10.3390/jcm13144244; Francis et al. 2009, doi:10.4103/0974-2069.58311 | Plausible: the 3-14 day range sits inside the published 5-20 day stays. The mapping of a category to a lesion is a proposal, and the urgent 14 days is between the switch (7) and Norwood (19.6) |
| Ward stay | 22 / 11 / 5 / 2 / 2 days, mean {ward_los_mean:.1f} days | Switch spell hospital stay median 19 days (IQR 14-24); TGA+VSD post-operative stay median 13 days (IQR 9-18); ToF repair stay 10.3 days (older than 90 days) to 28.9 days (30 days or younger); Norwood discharge at median age 24 days after operation at median age 9 days (about 15 days, derived) | Dorobantu et al. 2023, doi:10.1016/j.jacadv.2023.100407; Faateh et al. 2025, doi:10.1016/j.xjon.2024.10.015; Yang et al. 2019, doi:10.1186/s12872-019-0999-1; Staehler et al. 2023, doi:10.3389/fcvm.2023.1239477 | Plausible for urgent categories (22 and 11 days against 10-29); the routine categories (2 days) are day-case-like and have no source: awaiting source |
| CICU occupancy | {blocks[1]["occ"]} at 5 cases a week and 10 beds; ceiling 85% | No published range found (no CICU occupancy or utilisation figure). Candidate sources are still to be reviewed | none | Cannot judge: awaiting source |
| Waiting time | mean wait at surgery {blocks[1]["wait"]} weeks; {blocks[1]["over26"]} waiting 26+ weeks at week 52 | No paediatric cardiac wait range found. Uganda (low-resource, not comparable): 27 of 74 patients judged suitable (36%) were operated during the study; 13 deaths (15%) among those not operated | Grimaldi et al. 2014, doi:10.5830/cvja-2014-034 | Cannot judge for a high-income unit: awaiting source. A secondary summary quotes 32% and a 10-month median wait for Uganda; the source text read here shows 36% (27/74) and the 10-month wait was not re-verified |
| Weekly escalation by category | {det_model} | Untreated survival (death or loss of operability with no treatment at all, so upper bounds): ToF 66% at 1 y (0.8%/wk); complete AVSD 54% at 6 months (2.34%/wk); large VSD about 10% die in year 1 and 52% develop irreversible pulmonary vascular disease; TGA about 90% dead at 1 y | Saxena et al. 2019, doi:10.4103/apc.apc_32_19; hazard-calibration-output.md | Placeholders (12/7/4/2% a week) imply {" / ".join(format(cum(r), ".0%") for r in plc.rates)} escalating within 26 weeks, which is far above any sourced untreated death hazard for the lesions mapped to those categories. The literature-based rates are the sourced hazards by construction and are a proxy for escalation, not a measurement of it |
| Death or deterioration of children who are managed while waiting | the model has no deaths; escalation only | Norway, severe CHD (n = 2,359 live births): 10.0% died before age 2; 58% of those deaths (135 of 234) occurred before surgery, about 5.7% of the cohort over up to two years, mostly palliative-care or comorbid children | Wik et al. 2020, doi:10.1136/archdischild-2019-317581 | Not comparable like for like: a cohort-level, two-year figure that includes palliative-care children, against a weekly escalation of children on a list. It only bounds the answer: the weekly death risk of a managed child must be well below the untreated hazards (ToF 0.8%/wk would be 19% in 26 weeks untreated). The managed-patient escalation rate is still not sourced: awaiting source |
| Interstage mortality, HLHS | {deaths / hlhs_ops:.1%} simulated (input 8%) | 8% overall; 2.5% with home monitoring versus 10.3% without | Staehler et al. 2023, doi:10.3389/fcvm.2023.1239477 | Consistent (it is an input, so this checks the plumbing, not the clinical figure) |
| Long-wait multiplier | 1.49 (placeholder set) or 1.0 (literature set) | TGA+VSD repair after day 8 of life: composite post-operative complications aOR 1.49 (95% CI 1.02-2.15); the body of the paper reports 1.47; 24.0% versus 17.4% unadjusted; mortality not different | Faateh et al. 2025, doi:10.1016/j.xjon.2024.10.015 | Not supported as a generic waiting-list factor |

## 3. Reading the table

- The model's CICU stays and category rates are inside or near the orders of magnitude that the cited sources
  report for neonatal and infant cardiac surgery; occupancy and waits cannot be judged (no source). That is a face-validity statement, not validation: the sources describe
  other populations (England and Wales, the US, Norway, a small single-centre series) and none reports a waiting-list
  deterioration rate for a managed patient.
- The simulated mean stay (about 6.3 days) is above the nominal 5.2 days of the default mix because each stay is rounded
  up to whole days and because priority operates the long-stay urgent cases first, so they are over-represented among the
  operated patients.
- No source found gives CICU occupancy, a safe occupancy target, or waits for a high-income paediatric cardiac unit.
  Those rows stay "awaiting source" until further sources are reviewed.
- The category escalation placeholders are much higher than any sourced untreated hazard, which means the placeholder set
  probably overstates deterioration for lesions that are not deadlines. The literature-based set is the lower bound of what the
  sources can support; real managed-patient risk sits somewhere between and needs a clinician.
"""
    )
    OUT.write_text(text, encoding="utf-8")
    print(text[:3000])


if __name__ == "__main__":
    main()
